name: pytket-custatevec-test
channels:
  - conda-forge
dependencies:
  # The Python version will be injected by the GitHub Actions matrix
  - pip
  - pytket
  - cupy
  - cuquantum-python
  - pytest
  - pytket-qiskit
  - pytket-qulacs
  - mypy