# See https://docs.astral.sh/ruff/rules/
target-version = "py310"

line-length = 140

lint.select = [
  "E",    # pycodestyle Errors
  "W",    # pycodestyle Warnings

  "A",    # flake8-builtins
  "ANN",  # flake8-annotations
  "ARG",  # flake8-unused-arguments
  "B",    # flake8-Bugbear
  "BLE",  # flake8-blind-except
  "C4",   # flake8-comprehensions
  "C90",  # mccabe
  "COM",  # flake8-commas
  "D",    # pydocstyle
  "EM",   # flake8-errmsg
  "ERA",  # eradicate
  "EXE",  # flake8-executable
  "F",    # pyFlakes
  "FA",   # flake8-future-annotations
  "FBT",  # flake8-boolean-trap
  "FIX",  # flake8-fixme
  "FLY",  # flynt
  "FURB", # refurb
  "G",    # flake8-logging-format
  "I",    # isort
  "ICN",  # flake8-import-conventions
  "INP",  # flake8-no-pep420
  "INT",  # flake8-gettext
  "ISC",  # flake8-implicit-str-concat
  "LOG",  # flake8-logging
  "N",    # pep8-Naming
  "NPY",  # NumPy-specific
  "PERF", # Perflint
  "PGH",  # pygrep-hooks
  "PIE",  # flake8-pie
  "PL",   # pylint
  "PT",   # flake8-pytest-style
  "PTH",  # flake8-use-pathlib
  "PYI",  # flake8-pyi
  "Q",    # flake8-quotes
  "RET",  # flake8-return
  "RSE",  # flake8-raise
  "RUF",  # Ruff-specific
  "S",    # flake8-bandit (Security)
  "SIM",  # flake8-simplify
  "SLF",  # flake8-self
  "SLOT", # flake8-slots
  "T10",  # flake8-debugger
  # "T20",  # flake8-print
  "TD",   # flake8-todos
  "TID",  # flake8-tidy-imports
  "TRY",  # tryceratops
  "UP",   # pyupgrade
  "YTT",  # flake8-2020
]

lint.ignore = [
    "TRY003",  # Avoid using bare `except` clauses.
    "EM101",  # Logging statement uses `f-string` instead of lazy formatting.
    "EM102",  # String interpolation should be delayed to logging call.
    "PLR0913",  # Too many arguments in a function/method.
    "TD002",  # Missing `TODO` author.
    "TD003",  # Missing `TODO` colon.
    "TD004",  # Missing `TODO` description.
    "FIX002",  # Missing `FIXME` description.
    "B904",  # Within an `assertRaises` context, use `assertRaisesRegex` for better matching.
    "N802",  # Function name should be lowercase.
    "FBT001",  # Boolean positional value in function call.
    "FBT002",  # Boolean default value in function definition.
    "EXE002",  # Shebang is present but the file is not marked as executable.
    "ANN101", # Checks that instance method self arguments have type annotations.
    "PLC0414", # Checks for import aliases that do not rename the original package.
]

[lint.per-file-ignores]
"docs/*" = [
    "D100",  # Missing docstring in public module.
    "INP001",  # File is part of an implicit namespace package. Add an `__init__.py`.
]
"tests/*" = [
    "INP001",  # File is part of an implicit namespace package. Add an `__init__.py`.
    "S101",  # Use of `assert` detected.
    "D103",  # Missing docstring in public function.
    "N806",  # Variable in function should be lowercase.
    "ERA001", # Commented code
    "RUF100", # Unused noqa directive
]

[lint.pydocstyle]
convention = "google"
